### PR TITLE
Without adding dependences, re-enable secure RSA generation on Windows, Mac OS X, & Android

### PR DESCRIPTION
**Pull request by n8sh**

### CODE REVIEW

**Comment by shove70** [comment]
Thank you very much. I learned something from your submission!

**Comment by shove70** [comment]
There's no problem compiling it alone, but when a project relies on it, compiling and reporting link errors under macos, I need to configure - L???
（macOS）


Linking...
Undefined symbols for architecture x86_64:
  "_arcrandom", referenced from:
      __D6crypto5utils19ARC4RandomGenerator__T4nextTkZQiMFNbNiNfkkZk in libcrypto.a(utils_490_3a0.o)
      __D6crypto5utils19ARC4RandomGenerator__T4nextThZQiMFNbNiNfhhZh in libcrypto.a(utils_493_409.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: linker exited with status 1
/Library/D/dmd/bin/dmd failed with exit code 1.
  ^^^ Terminated, exit code: 2 ^^^
************  Build terminated.  ************

**Comment by shove70** [comment]
Yes, I removed arcrandom() and used arc4random_uniform() only.

**Comment by n8sh** [comment]
I am investigating this problem.

**Comment by n8sh** [comment]
I was able to reproduce the problem when using crypto from another project. It was solved by using `pragma(mangle, "arc4random")` to avoid the linker mysteriously changing "arc4random" to "_arc4random". Fix: https://github.com/shove70/crypto/pull/12

**Pull request merged**
